version: '3.7'
services:
  database:
    image: postgres:13
    container_name: "gringo_io"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
